cmake_minimum_required(VERSION 4.0)
project(SmallTest)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_subdirectory(Core)
#add_subdirectory(Core/Test)
add_subdirectory(strings)
add_subdirectory(build_compiler)
add_subdirectory(lsp_server)
add_subdirectory(ZMCore)
add_subdirectory(visualizer)
add_subdirectory(servant)
add_subdirectory(server)